### PR TITLE
add negativeAck to consumer

### LINKED ISSUE #60: Support manual negativeAcknowledge
Hi @sksamuel,

IIRC, negativeAck is not implemented, there is a reason for it or can pulsar4s support negativeAcknowledge?

### PR DESCRIPTION
**Pull request by KannarFr**
closes #60.

### CODE REVIEW

**Comment by KannarFr** [comment]
For the moment I got this, is JConsumer refer to the pulsar-api-client Consumer class which implements the negativeAcknowledge method:

```[error] pulsar4s/pulsar4s-core/src/main/scala/com/sksamuel/pulsar4s/Consumer.scala:98: value negativeAcknowledge is not a member of com.sksamuel.pulsar4s.JConsumer[T]
[error]   override def negativeAcknowledge(messageId: MessageId): Unit = consumer.negativeAcknowledge(messageId)
[error]                                                                           ^
[error] one error found```

**Comment by merlimat** [comment]
@KannarFr  negativeAcknowledge was added for 2.4 which is not released yet

**Comment by KannarFr** [comment]
@merlimat oh, my bad.

**Comment by KannarFr** [comment]
Even pulsar4s conflicts with Apache Pulsar v2.4.0.

**Comment by KannarFr** [comment]
@sksamuel now that v2.4.0 is released, can you help me bump this PR?

**Comment by gmethvin** [comment]
@KannarFr I already implemented this in https://github.com/sksamuel/pulsar4s/pull/44, including various other changes required to make it compile with Pulsar 2.4.

**Comment by sksamuel** [comment]
I will review this weekend.

**Comment by KannarFr** [comment]
@gmethvin okay, then I close this. Thanks.
